# Generated by Django 3.0.5 on 2020-04-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_challenge', '0002_auto_20200403_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='image_url',
        ),
    ]
