# Generated by Django 3.0.5 on 2020-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_challenge', '0003_remove_challenge_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
