# Generated by Django 3.0.5 on 2020-04-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_challenge', '0004_challenge_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exerciseList', to='fitness_challenge.Challenge'),
        ),
    ]
