# Generated by Django 3.0.5 on 2020-04-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_challenge', '0007_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='challenge_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengeResult', to='fitness_challenge.Challenge'),
        ),
    ]
