# Generated by Django 3.0.5 on 2020-04-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_challenge', '0009_auto_20200406_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.IntegerField(),
        ),
    ]
