# Generated by Django 3.0.5 on 2020-04-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_challenge', '0011_auto_20200407_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
